version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "live"
    default_labels: ["dependencies"]
    automerged_updates:
      - match:
          dependency_type: all
          update_type: in_range
